import type { Config, Data } from '@measured/puck';

const textField = { type: 'text' } as const;
const areaField = { type: 'textarea' } as const;

export const landingPuckConfig: Config = {
  components: {
    LandingHero: { fields: { eyebrow: textField, title: textField, subtitle: areaField, primaryCta: textField, backgroundColor: textField, textColor: textField, accentColor: textField }, defaultProps: { eyebrow: 'AI Operations Landing', title: 'Transformă catalogul GadgetHub în comenzi online în câteva minute.', subtitle: 'Hero, beneficii și call-to-action într-o pagină completă generată cu date demo despre gadgeturi.', primaryCta: 'Programează demo', backgroundColor: '#312e81', textColor: '#ffffff', accentColor: '#ffffff' }, render: (p: any) => <section className="rounded-[2rem] px-6 py-24 text-center" style={{ backgroundColor: p.backgroundColor, color: p.textColor }}><span className="rounded-full bg-white/10 px-4 py-2 text-sm font-bold">{p.eyebrow}</span><h1 className="mx-auto mt-8 max-w-5xl text-5xl font-black leading-tight md:text-7xl">{p.title}</h1><p className="mx-auto mt-6 max-w-2xl text-xl opacity-80">{p.subtitle}</p><button className="mt-10 rounded-2xl px-8 py-4 font-black text-indigo-950" style={{ backgroundColor: p.accentColor }}>{p.primaryCta}</button></section> },
    BenefitsGrid: { fields: { title: textField, benefit1Title: textField, benefit1Text: areaField, benefit2Title: textField, benefit2Text: areaField, benefit3Title: textField, benefit3Text: areaField }, defaultProps: { title: 'Beneficii GadgetHub', benefit1Title: 'Analiză instant', benefit1Text: 'Identifici produsele și campaniile cu cel mai mare potențial.', benefit2Title: 'Rapoarte AI', benefit2Text: 'Primești sumar automat pentru vânzări, stocuri și lead-uri.', benefit3Title: 'Integrări rapide', benefit3Text: 'Conectezi formulare, CRM și comenzi fără backend nou.' }, render: (p: any) => <section className="px-6 py-16"><h2 className="text-center text-4xl font-black text-slate-950">{p.title}</h2><div className="mx-auto mt-8 grid max-w-6xl gap-6 md:grid-cols-3">{[[p.benefit1Title, p.benefit1Text], [p.benefit2Title, p.benefit2Text], [p.benefit3Title, p.benefit3Text]].map(([title, text]) => <div key={title} className="rounded-3xl border border-slate-200 p-8 shadow-sm"><h3 className="text-2xl font-black text-slate-900">{title}</h3><p className="mt-3 text-slate-500">{text}</p></div>)}</div></section> },
    Testimonials: { fields: { title: textField, quote1: areaField, author1: textField, quote2: areaField, author2: textField }, defaultProps: { title: 'Ce spun echipele', quote1: 'Am lansat o pagină de campanie GadgetHub în aceeași zi.', author1: 'Irina Popescu, GadgetHub.ro', quote2: 'Fluxul demo ne-a ajutat să validăm rapid comenzile online.', author2: 'Andrei Ionescu, TechWear' }, render: (p: any) => <section className="bg-slate-50 px-6 py-16"><h2 className="text-center text-3xl font-black text-slate-950">{p.title}</h2><div className="mx-auto mt-8 grid max-w-5xl gap-5 md:grid-cols-2">{[[p.quote1, p.author1], [p.quote2, p.author2]].map(([quote, author]) => <blockquote key={author} className="rounded-3xl bg-white p-6 shadow-sm"><p className="text-lg font-semibold text-slate-700">“{quote}”</p><footer className="mt-4 text-sm font-black text-indigo-600">{author}</footer></blockquote>)}</div></section> },
    LeadFormBlock: { fields: { title: textField, description: areaField, buttonLabel: textField, gdprText: areaField }, defaultProps: { title: 'Primește audit gratuit', description: 'Completează datele și echipa noastră revine cu recomandări pentru catalogul tău.', buttonLabel: 'Trimite cererea', gdprText: 'Sunt de acord să fiu contactat pentru demo.' }, render: (p: any) => <section className="px-6 py-16"><div className="mx-auto max-w-3xl rounded-[2rem] bg-slate-950 p-8 text-white"><h2 className="text-3xl font-black">{p.title}</h2><p className="mt-2 text-slate-300">{p.description}</p><div className="mt-6 grid gap-3 md:grid-cols-2"><input readOnly placeholder="Nume" className="rounded-xl border-0 px-4 py-3 text-slate-950" /><input readOnly placeholder="Email" className="rounded-xl border-0 px-4 py-3 text-slate-950" /></div><p className="mt-4 text-xs text-slate-400">{p.gdprText}</p><button className="mt-5 rounded-xl bg-white px-5 py-3 font-black text-slate-950">{p.buttonLabel}</button></div></section> },
    PricingCta: { fields: { title: textField, price: textField, description: areaField, buttonLabel: textField }, defaultProps: { title: 'Plan recomandat', price: 'De la 499 RON/lună', description: 'Include landing, captură lead-uri și rapoarte AI demo.', buttonLabel: 'Alege planul' }, render: (p: any) => <section className="px-6 py-12 text-center"><div className="mx-auto max-w-xl rounded-[2rem] border border-indigo-100 bg-indigo-50 p-8"><h2 className="text-3xl font-black text-slate-950">{p.title}</h2><p className="mt-4 text-5xl font-black text-indigo-700">{p.price}</p><p className="mt-4 text-slate-600">{p.description}</p><button className="mt-6 rounded-xl bg-indigo-600 px-6 py-3 font-black text-white">{p.buttonLabel}</button></div></section> },
    FaqBlock: { fields: { question1: textField, answer1: areaField, question2: textField, answer2: areaField, question3: textField, answer3: areaField }, defaultProps: { question1: 'Este nevoie de backend?', answer1: 'Nu pentru acest demo; datele sunt gestionate în browser.', question2: 'Pot edita textele?', answer2: 'Da, componentele sunt editabile direct în Puck.', question3: 'Unde se salvează?', answer3: 'Datele publicate sunt salvate în IndexedDB.' }, render: (p: any) => <section className="px-6 py-12"><div className="mx-auto max-w-4xl space-y-3">{[[p.question1, p.answer1], [p.question2, p.answer2], [p.question3, p.answer3]].map(([q, a]) => <details key={q} className="rounded-2xl border border-slate-200 p-5" open><summary className="font-black text-slate-950">{q}</summary><p className="mt-2 text-slate-600">{a}</p></details>)}</div></section> },
    FinalCta: { fields: { title: textField, subtitle: areaField, buttonLabel: textField, backgroundColor: textField }, defaultProps: { title: 'Gata să începi?', subtitle: 'Discută cu echipa GadgetHub despre oferta de gadgeturi.', buttonLabel: 'Discută cu un consultant', backgroundColor: '#0f172a' }, render: (p: any) => <section className="m-6 rounded-[2rem] p-10 text-center text-white" style={{ backgroundColor: p.backgroundColor }}><h2 className="text-4xl font-black">{p.title}</h2><p className="mt-3 text-slate-300">{p.subtitle}</p><button className="mt-6 rounded-xl bg-white px-6 py-3 font-black text-slate-950">{p.buttonLabel}</button></section> },
    LandingFooter: { fields: { companyName: textField, legalText: textField }, defaultProps: { companyName: 'GadgetHub', legalText: '© 2026 GadgetHub. Toate drepturile rezervate.' }, render: (p: any) => <footer className="flex flex-col gap-2 border-t border-slate-200 px-6 py-8 text-sm text-slate-500 md:flex-row md:items-center md:justify-between"><strong className="text-slate-950">{p.companyName}</strong><span>{p.legalText}</span></footer> }
  }
} as Config;

export const defaultLandingPuckData: Data = { root: { props: {} }, content: [
  { type: 'LandingHero', props: { id: 'landing-hero', eyebrow: 'AI Operations Landing', title: 'Transformă catalogul GadgetHub în comenzi online în câteva minute.', subtitle: 'Hero, beneficii și call-to-action într-o pagină completă generată cu date demo despre gadgeturi.', primaryCta: 'Programează demo', backgroundColor: '#312e81', textColor: '#ffffff', accentColor: '#ffffff' } },
  { type: 'BenefitsGrid', props: { id: 'benefits-grid', title: 'Beneficii GadgetHub', benefit1Title: 'Analiză instant', benefit1Text: 'Identifici produsele și campaniile cu cel mai mare potențial.', benefit2Title: 'Rapoarte AI', benefit2Text: 'Primești sumar automat pentru vânzări, stocuri și lead-uri.', benefit3Title: 'Integrări rapide', benefit3Text: 'Conectezi formulare, CRM și comenzi fără backend nou.' } },
  { type: 'Testimonials', props: { id: 'testimonials', title: 'Ce spun echipele', quote1: 'Am lansat o pagină de campanie GadgetHub în aceeași zi.', author1: 'Irina Popescu, GadgetHub.ro', quote2: 'Fluxul demo ne-a ajutat să validăm rapid comenzile online.', author2: 'Andrei Ionescu, TechWear' } },
  { type: 'LeadFormBlock', props: { id: 'lead-form', title: 'Primește audit gratuit', description: 'Completează datele și echipa noastră revine cu recomandări pentru catalogul tău.', buttonLabel: 'Trimite cererea', gdprText: 'Sunt de acord să fiu contactat pentru demo.' } },
  { type: 'PricingCta', props: { id: 'pricing-cta', title: 'Plan recomandat', price: 'De la 499 RON/lună', description: 'Include landing, captură lead-uri și rapoarte AI demo.', buttonLabel: 'Alege planul' } },
  { type: 'FaqBlock', props: { id: 'faq-block', question1: 'Este nevoie de backend?', answer1: 'Nu pentru acest demo; datele sunt gestionate în browser.', question2: 'Pot edita textele?', answer2: 'Da, componentele sunt editabile direct în Puck.', question3: 'Unde se salvează?', answer3: 'Datele publicate sunt salvate în IndexedDB.' } },
  { type: 'FinalCta', props: { id: 'final-cta', title: 'Gata să începi?', subtitle: 'Discută cu echipa GadgetHub despre oferta de gadgeturi.', buttonLabel: 'Discută cu un consultant', backgroundColor: '#0f172a' } },
  { type: 'LandingFooter', props: { id: 'landing-footer', companyName: 'GadgetHub', legalText: '© 2026 GadgetHub. Toate drepturile rezervate.' } }
] };
